# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: key_types.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'key_types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fkey_types.proto\x12\x0f\x62\x61gz_index.keys\"\x1a\n\tStringKey\x12\r\n\x05value\x18\x01 \x01(\t\"\x19\n\x08Int64Key\x12\r\n\x05value\x18\x01 \x01(\x03\"\x1f\n\x0eTupleStringKey\x12\r\n\x05value\x18\x01 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'key_types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STRINGKEY']._serialized_start=36
  _globals['_STRINGKEY']._serialized_end=62
  _globals['_INT64KEY']._serialized_start=64
  _globals['_INT64KEY']._serialized_end=89
  _globals['_TUPLESTRINGKEY']._serialized_start=91
  _globals['_TUPLESTRINGKEY']._serialized_end=122
# @@protoc_insertion_point(module_scope)
