# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\"-\n\nHashRecord\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\x12\n\nrecord_ids\x18\x02 \x03(\x03\"*\n\nHashBucket\x12\x1c\n\x07records\x18\x01 \x03(\x0b\x32\x0b.HashRecord\"9\n\x0bPostingList\x12\x12\n\nrecord_ids\x18\x01 \x03(\x03\x12\x16\n\x0erecord_offsets\x18\x02 \x03(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HASHRECORD']._serialized_start=18
  _globals['_HASHRECORD']._serialized_end=63
  _globals['_HASHBUCKET']._serialized_start=65
  _globals['_HASHBUCKET']._serialized_end=107
  _globals['_POSTINGLIST']._serialized_start=109
  _globals['_POSTINGLIST']._serialized_end=166
# @@protoc_insertion_point(module_scope)
